// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hrbbdnzsprwgfviobecc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhyYmJkbnpzcHJ3Z2Z2aW9iZWNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1MDQwMDIsImV4cCI6MjA1ODA4MDAwMn0.kVKgKVWJLDlRELDHFWxfjbLevb5zmVRTBLKXL13a4KM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);